allowBuilds:
  '@prisma/engines': set this to true or false
  core-js: false
  prisma: set this to true or false
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@ionic/core@8.8.11'
  - '@ionic/react@8.8.11'
packages:
  - 'app/*'
